// ============================================================
// MOCK DATA - Realistic Insurance Domain Data
// ============================================================
import type { Policy } from '../types/policy.types';
import type { ServiceRequest, RequestCatalogItem } from '../types/request.types';

export const mockPolicies: Policy[] = [
  {
    id: 'pol-001',
    policyNumber: 'LI-2021-00147832',
    productCode: 'TERM-SHIELD-PLUS',
    productName: 'Term Shield Plus',
    policyType: 'Term',
    status: 'Active',
    issueDate: '2021-03-15',
    commencementDate: '2021-04-01',
    maturityDate: '2051-04-01',
    policyTerm: 30,
    policyTermUnit: 'Years',
    policyHolder: {
      id: 'cust-001',
      customerId: 'CUST00147832',
      salutation: 'Mr.',
      firstName: 'Rajesh',
      lastName: 'Sharma',
      fullName: 'Rajesh Sharma',
      dateOfBirth: '1985-07-22',
      gender: 'Male',
      pan: 'ABCPS1234D',
      aadhaar: '****-****-4321',
      email: 'rajesh.sharma@email.com',
      mobile: '9876543210',
      kycStatus: 'Verified',
      kycVerifiedOn: '2021-03-10',
      address: {
        id: 'addr-001',
        line1: '42, Sunrise Apartments',
        line2: 'Sector 14, Dwarka',
        city: 'New Delhi',
        state: 'Delhi',
        pincode: '110078',
        country: 'India',
        addressType: 'Permanent',
        isVerified: true,
      },
      communicationPreference: {
        email: true,
        sms: true,
        whatsApp: true,
        post: false,
        language: 'English',
      },
      bankAccount: {
        id: 'bank-001',
        accountNumber: '****4521',
        accountHolderName: 'Rajesh Sharma',
        ifscCode: 'HDFC0001234',
        bankName: 'HDFC Bank',
        branch: 'Dwarka Branch',
        accountType: 'Savings',
        isVerified: true,
        verifiedOn: '2021-03-12',
        isPrimary: true,
      },
      createdOn: '2021-03-10',
      modifiedOn: '2024-01-15',
    },
    nominees: [
      {
        id: 'nom-001',
        name: 'Priya Sharma',
        relationship: 'Spouse',
        dateOfBirth: '1988-03-14',
        sharePercentage: 100,
        isPrimary: true,
        isMinor: false,
        mobile: '9876543211',
        email: 'priya.sharma@email.com',
      },
    ],
    premiumDetails: {
      annualPremium: 24800,
      premiumMode: 'Yearly',
      modalPremium: 24800,
      nextPremiumDueDate: '2025-04-01',
      lastPremiumPaidDate: '2024-04-02',
      totalPremiumPaid: 86800,
      premiumPayingTerm: 30,
      premiumPayingTermUnit: 'Years',
      autoDebit: true,
    },
    coverage: {
      sumAssured: 10000000,
      deathBenefit: 10000000,
    },
    totalRequests: 3,
    openRequests: 1,
    createdOn: '2021-03-15',
    modifiedOn: '2024-06-10',
    branchCode: 'DEL-DWK-001',
    agentCode: 'AGT-10234',
    channelType: 'Bancassurance',
  },
  {
    id: 'pol-002',
    policyNumber: 'EN-2019-00089541',
    productCode: 'ENDOW-CLASSIC',
    productName: 'Endowment Classic',
    policyType: 'Endowment',
    status: 'Active',
    issueDate: '2019-08-20',
    commencementDate: '2019-09-01',
    maturityDate: '2039-09-01',
    policyTerm: 20,
    policyTermUnit: 'Years',
    policyHolder: {
      id: 'cust-002',
      customerId: 'CUST00089541',
      salutation: 'Ms.',
      firstName: 'Anita',
      lastName: 'Patel',
      fullName: 'Anita Patel',
      dateOfBirth: '1979-11-05',
      gender: 'Female',
      pan: 'DEFAP5678G',
      email: 'anita.patel@email.com',
      mobile: '8765432109',
      kycStatus: 'Verified',
      kycVerifiedOn: '2019-08-15',
      address: {
        id: 'addr-002',
        line1: '15, Rose Garden Society',
        line2: 'Satellite Road',
        city: 'Ahmedabad',
        state: 'Gujarat',
        pincode: '380015',
        country: 'India',
        addressType: 'Permanent',
        isVerified: true,
      },
      communicationPreference: {
        email: true,
        sms: true,
        whatsApp: false,
        post: true,
        language: 'Gujarati',
      },
      createdOn: '2019-08-15',
      modifiedOn: '2023-11-20',
    },
    nominees: [
      {
        id: 'nom-002',
        name: 'Vikram Patel',
        relationship: 'Spouse',
        dateOfBirth: '1977-06-30',
        sharePercentage: 60,
        isPrimary: true,
        isMinor: false,
      },
      {
        id: 'nom-003',
        name: 'Rohan Patel',
        relationship: 'Son',
        dateOfBirth: '2005-02-18',
        sharePercentage: 40,
        isPrimary: false,
        isMinor: false,
        guardianName: 'Vikram Patel',
        guardianRelationship: 'Father',
      },
    ],
    premiumDetails: {
      annualPremium: 52400,
      premiumMode: 'HalfYearly',
      modalPremium: 26800,
      nextPremiumDueDate: '2024-09-01',
      lastPremiumPaidDate: '2024-03-01',
      totalPremiumPaid: 418400,
      premiumPayingTerm: 20,
      premiumPayingTermUnit: 'Years',
      autoDebit: false,
    },
    coverage: {
      sumAssured: 1000000,
      deathBenefit: 1500000,
      maturityBenefit: 1800000,
    },
    totalRequests: 5,
    openRequests: 0,
    createdOn: '2019-08-20',
    modifiedOn: '2024-03-05',
    branchCode: 'AHM-SAT-002',
    channelType: 'Agency',
  },
  {
    id: 'pol-003',
    policyNumber: 'ULIP-2022-00234156',
    productCode: 'ULIP-GROW-PLUS',
    productName: 'ULIP Growth Plus',
    policyType: 'ULIP',
    status: 'Active',
    issueDate: '2022-01-10',
    commencementDate: '2022-02-01',
    maturityDate: '2037-02-01',
    policyTerm: 15,
    policyTermUnit: 'Years',
    policyHolder: {
      id: 'cust-003',
      customerId: 'CUST00234156',
      salutation: 'Mr.',
      firstName: 'Suresh',
      lastName: 'Mehta',
      fullName: 'Suresh Mehta',
      dateOfBirth: '1982-04-18',
      gender: 'Male',
      pan: 'GHISM2345H',
      email: 'suresh.mehta@email.com',
      mobile: '7654321098',
      kycStatus: 'Verified',
      kycVerifiedOn: '2022-01-05',
      address: {
        id: 'addr-003',
        line1: 'C-304, Prestige Tower',
        line2: 'MG Road',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560001',
        country: 'India',
        addressType: 'Correspondence',
        isVerified: true,
      },
      communicationPreference: {
        email: true,
        sms: true,
        whatsApp: true,
        post: false,
        language: 'English',
      },
      createdOn: '2022-01-05',
      modifiedOn: '2024-05-22',
    },
    nominees: [
      {
        id: 'nom-004',
        name: 'Kavitha Mehta',
        relationship: 'Spouse',
        dateOfBirth: '1984-09-10',
        sharePercentage: 100,
        isPrimary: true,
        isMinor: false,
      },
    ],
    premiumDetails: {
      annualPremium: 120000,
      premiumMode: 'Monthly',
      modalPremium: 10000,
      nextPremiumDueDate: '2024-09-01',
      lastPremiumPaidDate: '2024-08-01',
      totalPremiumPaid: 360000,
      premiumPayingTerm: 15,
      premiumPayingTermUnit: 'Years',
      autoDebit: true,
    },
    coverage: {
      sumAssured: 1200000,
      deathBenefit: 1200000,
    },
    totalRequests: 2,
    openRequests: 2,
    createdOn: '2022-01-10',
    modifiedOn: '2024-07-15',
    branchCode: 'BLR-MGR-003',
    channelType: 'Direct',
  },
];

export const mockRequestCatalogue: RequestCatalogItem[] = [
  {
    id: 'cat-001',
    requestCode: 'ADDR_CHG',
    requestName: 'Address Change',
    description: 'Update your residential or correspondence address on record',
    category: 'Profile Update',
    slaHours: 48,
    slaDays: 2,
    requiresApproval: true,
    approvalLevels: 1,
    eligibilityRules: [
      {
        id: 'rule-001',
        ruleCode: 'POLICY_ACTIVE',
        ruleName: 'Policy Must Be Active',
        ruleDescription: 'Policy status must be Active to request address change',
        ruleType: 'PolicyStatus',
        operator: 'equals',
        fieldName: 'status',
        expectedValue: 'Active',
        errorMessage: 'Address change is only allowed for active policies',
        isMandatory: true,
        sequence: 1,
      },
      {
        id: 'rule-002',
        ruleCode: 'KYC_VALID',
        ruleName: 'KYC Must Be Valid',
        ruleDescription: 'Customer KYC status must be Verified',
        ruleType: 'KYCStatus',
        operator: 'equals',
        fieldName: 'policyHolder.kycStatus',
        expectedValue: 'Verified',
        errorMessage: 'Please complete KYC verification before requesting address change',
        isMandatory: true,
        sequence: 2,
      },
    ],
    requiredDocuments: [
      {
        id: 'doc-001',
        documentCode: 'ADDR_PROOF',
        documentName: 'Address Proof',
        description: 'Valid address proof (Aadhaar / Utility Bill / Passport)',
        isMandatory: true,
        acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
        maxSizeInMB: 5,
        instructions: 'Document should not be older than 3 months',
      },
      {
        id: 'doc-002',
        documentCode: 'SELF_DEC',
        documentName: 'Self Declaration Form',
        description: 'Signed self-declaration form',
        isMandatory: false,
        acceptedFormats: ['.pdf'],
        maxSizeInMB: 2,
      },
    ],
    formSchema: {
      isMultiStep: false,
      sections: [
        {
          id: 'sec-addr-new',
          title: 'New Address Details',
          fields: [
            {
              id: 'fld-addr-type',
              fieldName: 'addressType',
              fieldLabel: 'Address Type',
              fieldType: 'select',
              isRequired: true,
              options: [
                { label: 'Permanent Address', value: 'Permanent' },
                { label: 'Correspondence Address', value: 'Correspondence' },
                { label: 'Both', value: 'Both' },
              ],
              displayOrder: 1,
            },
            {
              id: 'fld-addr-line1',
              fieldName: 'newAddressLine1',
              fieldLabel: 'Address Line 1',
              fieldType: 'text',
              isRequired: true,
              placeholder: 'House/Flat No., Building Name',
              displayOrder: 2,
              columnSpan: 2,
              validationRules: [
                { type: 'maxLength', value: 200, message: 'Maximum 200 characters allowed' },
              ],
            },
            {
              id: 'fld-addr-line2',
              fieldName: 'newAddressLine2',
              fieldLabel: 'Address Line 2',
              fieldType: 'text',
              isRequired: false,
              placeholder: 'Street, Area, Locality',
              displayOrder: 3,
              columnSpan: 2,
            },
            {
              id: 'fld-city',
              fieldName: 'newCity',
              fieldLabel: 'City',
              fieldType: 'text',
              isRequired: true,
              displayOrder: 4,
            },
            {
              id: 'fld-state',
              fieldName: 'newState',
              fieldLabel: 'State',
              fieldType: 'select',
              isRequired: true,
              options: [],
              displayOrder: 5,
            },
            {
              id: 'fld-pin',
              fieldName: 'newPincode',
              fieldLabel: 'Pincode',
              fieldType: 'text',
              isRequired: true,
              displayOrder: 6,
              validationRules: [
                { type: 'pattern', value: '^[1-9][0-9]{5}$', message: 'Enter valid 6-digit pincode' },
              ],
            },
          ],
        },
      ],
    },
    isActive: true,
    displayOrder: 1,
    icon: 'Location',
    estimatedTime: '2-3 business days',
    tags: ['address', 'profile', 'personal'],
  },
  {
    id: 'cat-002',
    requestCode: 'NOM_CHG',
    requestName: 'Nominee Change',
    description: 'Add, update, or remove nominee details on your policy',
    category: 'Policy Modification',
    slaHours: 72,
    slaDays: 3,
    requiresApproval: true,
    approvalLevels: 2,
    eligibilityRules: [
      {
        id: 'rule-003',
        ruleCode: 'POLICY_ACTIVE_NOM',
        ruleName: 'Policy Must Be Active',
        ruleDescription: 'Policy must be active for nominee change',
        ruleType: 'PolicyStatus',
        operator: 'equals',
        fieldName: 'status',
        expectedValue: 'Active',
        errorMessage: 'Nominee change is only allowed for active policies',
        isMandatory: true,
        sequence: 1,
      },
      {
        id: 'rule-004',
        ruleCode: 'NOM_NOT_LOCKED',
        ruleName: 'Nominee Not Locked',
        ruleDescription: 'Nominee should not be under legal lock',
        ruleType: 'BusinessRule',
        operator: 'equals',
        fieldName: 'isNomineeLocked',
        expectedValue: false,
        errorMessage: 'Nominee change is restricted due to legal lock. Please contact our legal team.',
        isMandatory: true,
        sequence: 2,
      },
    ],
    requiredDocuments: [
      {
        id: 'doc-003',
        documentCode: 'NOM_ID_PROOF',
        documentName: 'Nominee Identity Proof',
        description: 'Valid ID proof of new nominee (Aadhaar / PAN / Passport)',
        isMandatory: true,
        acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
        maxSizeInMB: 5,
      },
      {
        id: 'doc-004',
        documentCode: 'NOM_FORM',
        documentName: 'Nominee Change Form',
        description: 'Signed nominee change request form',
        isMandatory: true,
        acceptedFormats: ['.pdf'],
        maxSizeInMB: 2,
      },
    ],
    formSchema: {
      isMultiStep: true,
      totalSteps: 2,
      sections: [
        {
          id: 'sec-nom-info',
          title: 'New Nominee Information',
          step: 1,
          fields: [
            {
              id: 'fld-nom-name',
              fieldName: 'nomineeName',
              fieldLabel: 'Nominee Full Name',
              fieldType: 'text',
              isRequired: true,
              displayOrder: 1,
              columnSpan: 2,
            },
            {
              id: 'fld-nom-rel',
              fieldName: 'nomineeRelationship',
              fieldLabel: 'Relationship with Policyholder',
              fieldType: 'select',
              isRequired: true,
              options: [],
              displayOrder: 2,
            },
            {
              id: 'fld-nom-dob',
              fieldName: 'nomineeDob',
              fieldLabel: 'Date of Birth',
              fieldType: 'date',
              isRequired: true,
              displayOrder: 3,
            },
            {
              id: 'fld-nom-share',
              fieldName: 'nomineeShare',
              fieldLabel: 'Share Percentage (%)',
              fieldType: 'number',
              isRequired: true,
              displayOrder: 4,
              validationRules: [
                { type: 'min', value: 1, message: 'Minimum 1%' },
                { type: 'max', value: 100, message: 'Maximum 100%' },
              ],
            },
          ],
        },
        {
          id: 'sec-nom-contact',
          title: 'Nominee Contact Details',
          step: 2,
          fields: [
            {
              id: 'fld-nom-mobile',
              fieldName: 'nomineeMobile',
              fieldLabel: 'Mobile Number',
              fieldType: 'phone',
              isRequired: false,
              displayOrder: 1,
            },
            {
              id: 'fld-nom-email',
              fieldName: 'nomineeEmail',
              fieldLabel: 'Email Address',
              fieldType: 'email',
              isRequired: false,
              displayOrder: 2,
            },
          ],
        },
      ],
    },
    isActive: true,
    displayOrder: 2,
    icon: 'People',
    estimatedTime: '3-5 business days',
    tags: ['nominee', 'policy', 'modification'],
  },
  {
    id: 'cat-003',
    requestCode: 'PREM_MODE_CHG',
    requestName: 'Premium Mode Change',
    description: 'Change your premium payment frequency (Monthly / Quarterly / Half-Yearly / Yearly)',
    category: 'Premium Management',
    slaHours: 48,
    slaDays: 2,
    requiresApproval: false,
    approvalLevels: 0,
    eligibilityRules: [
      {
        id: 'rule-005',
        ruleCode: 'POLICY_ACTIVE_PREM',
        ruleName: 'Policy Must Be Active',
        ruleDescription: 'Policy must be active for premium mode change',
        ruleType: 'PolicyStatus',
        operator: 'equals',
        fieldName: 'status',
        expectedValue: 'Active',
        errorMessage: 'Premium mode change is only allowed for active policies',
        isMandatory: true,
        sequence: 1,
      },
      {
        id: 'rule-006',
        ruleCode: 'NO_UPCOMING_PREMIUM',
        ruleName: 'No Upcoming Premium Generated',
        ruleDescription: 'Mode change not allowed if upcoming premium notice already generated',
        ruleType: 'BusinessRule',
        operator: 'equals',
        fieldName: 'hasUpcomingPremiumNotice',
        expectedValue: false,
        errorMessage: 'Premium mode change cannot be done as premium notice for next due date is already generated',
        isMandatory: true,
        sequence: 2,
      },
    ],
    requiredDocuments: [],
    formSchema: {
      isMultiStep: false,
      sections: [
        {
          id: 'sec-prem-mode',
          title: 'New Premium Mode',
          fields: [
            {
              id: 'fld-new-mode',
              fieldName: 'newPremiumMode',
              fieldLabel: 'Select New Premium Mode',
              fieldType: 'radio',
              isRequired: true,
              options: [
                { label: 'Monthly', value: 'Monthly', description: 'Pay every month' },
                { label: 'Quarterly', value: 'Quarterly', description: 'Pay every 3 months' },
                { label: 'Half-Yearly', value: 'HalfYearly', description: 'Pay every 6 months' },
                { label: 'Yearly', value: 'Yearly', description: 'Pay once a year' },
              ],
              displayOrder: 1,
            },
            {
              id: 'fld-effective-date',
              fieldName: 'effectiveDate',
              fieldLabel: 'Effective From',
              fieldType: 'date',
              isRequired: true,
              helpText: 'New mode will apply from next premium due date',
              displayOrder: 2,
              isReadOnly: true,
            },
          ],
        },
      ],
    },
    isActive: true,
    displayOrder: 3,
    icon: 'CalendarSettings',
    estimatedTime: '1-2 business days',
    tags: ['premium', 'payment', 'mode'],
  },
  {
    id: 'cat-004',
    requestCode: 'MOB_UPD',
    requestName: 'Mobile Number Update',
    description: 'Update your registered mobile number',
    category: 'Profile Update',
    slaHours: 24,
    slaDays: 1,
    requiresApproval: false,
    approvalLevels: 0,
    eligibilityRules: [
      {
        id: 'rule-007',
        ruleCode: 'POLICY_ACTIVE_MOB',
        ruleName: 'Policy Must Be Active',
        ruleDescription: 'Policy must be active',
        ruleType: 'PolicyStatus',
        operator: 'equals',
        fieldName: 'status',
        expectedValue: 'Active',
        errorMessage: 'This service is only available for active policies',
        isMandatory: true,
        sequence: 1,
      },
    ],
    requiredDocuments: [
      {
        id: 'doc-005',
        documentCode: 'ID_PROOF',
        documentName: 'Identity Proof',
        description: 'Valid Government ID proof',
        isMandatory: true,
        acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
        maxSizeInMB: 5,
      },
    ],
    formSchema: {
      isMultiStep: false,
      sections: [
        {
          id: 'sec-mob',
          title: 'New Mobile Number',
          fields: [
            {
              id: 'fld-new-mob',
              fieldName: 'newMobile',
              fieldLabel: 'New Mobile Number',
              fieldType: 'phone',
              isRequired: true,
              placeholder: '10-digit mobile number',
              displayOrder: 1,
              validationRules: [
                { type: 'pattern', value: '^[6-9][0-9]{9}$', message: 'Enter valid 10-digit Indian mobile number' },
              ],
            },
            {
              id: 'fld-confirm-mob',
              fieldName: 'confirmMobile',
              fieldLabel: 'Confirm Mobile Number',
              fieldType: 'phone',
              isRequired: true,
              placeholder: 'Re-enter mobile number',
              displayOrder: 2,
            },
          ],
        },
      ],
    },
    isActive: true,
    displayOrder: 4,
    icon: 'Phone',
    estimatedTime: '1 business day',
    tags: ['mobile', 'contact', 'profile'],
  },
  {
    id: 'cat-005',
    requestCode: 'BANK_CHG',
    requestName: 'Bank Account Change',
    description: 'Update bank account for premium auto-debit and claim payments',
    category: 'Financial',
    slaHours: 96,
    slaDays: 4,
    requiresApproval: true,
    approvalLevels: 2,
    eligibilityRules: [
      {
        id: 'rule-008',
        ruleCode: 'POLICY_ACTIVE_BANK',
        ruleName: 'Policy Must Be Active',
        ruleDescription: 'Policy must be active for bank account change',
        ruleType: 'PolicyStatus',
        operator: 'equals',
        fieldName: 'status',
        expectedValue: 'Active',
        errorMessage: 'Bank account change is only allowed for active policies',
        isMandatory: true,
        sequence: 1,
      },
    ],
    requiredDocuments: [
      {
        id: 'doc-006',
        documentCode: 'CANCELLED_CHEQUE',
        documentName: 'Cancelled Cheque',
        description: 'Cancelled cheque of new bank account',
        isMandatory: true,
        acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
        maxSizeInMB: 2,
      },
      {
        id: 'doc-007',
        documentCode: 'BANK_PASSBOOK',
        documentName: 'Bank Passbook / Statement',
        description: 'First page of bank passbook or recent bank statement',
        isMandatory: false,
        acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
        maxSizeInMB: 5,
      },
    ],
    formSchema: {
      isMultiStep: false,
      sections: [
        {
          id: 'sec-bank',
          title: 'New Bank Account Details',
          fields: [
            {
              id: 'fld-acc-holder',
              fieldName: 'accountHolderName',
              fieldLabel: 'Account Holder Name',
              fieldType: 'text',
              isRequired: true,
              displayOrder: 1,
              columnSpan: 2,
            },
            {
              id: 'fld-acc-num',
              fieldName: 'accountNumber',
              fieldLabel: 'Account Number',
              fieldType: 'text',
              isRequired: true,
              displayOrder: 2,
            },
            {
              id: 'fld-acc-num-confirm',
              fieldName: 'confirmAccountNumber',
              fieldLabel: 'Confirm Account Number',
              fieldType: 'text',
              isRequired: true,
              displayOrder: 3,
            },
            {
              id: 'fld-ifsc',
              fieldName: 'ifscCode',
              fieldLabel: 'IFSC Code',
              fieldType: 'text',
              isRequired: true,
              displayOrder: 4,
              validationRules: [
                { type: 'pattern', value: '^[A-Z]{4}0[A-Z0-9]{6}$', message: 'Enter valid IFSC code' },
              ],
            },
            {
              id: 'fld-bank-name',
              fieldName: 'bankName',
              fieldLabel: 'Bank Name',
              fieldType: 'text',
              isRequired: true,
              displayOrder: 5,
              isReadOnly: true,
              helpText: 'Auto-populated from IFSC code',
            },
            {
              id: 'fld-acc-type',
              fieldName: 'accountType',
              fieldLabel: 'Account Type',
              fieldType: 'select',
              isRequired: true,
              options: [
                { label: 'Savings Account', value: 'Savings' },
                { label: 'Current Account', value: 'Current' },
              ],
              displayOrder: 6,
            },
          ],
        },
      ],
    },
    isActive: true,
    displayOrder: 5,
    icon: 'CreditCardMagnifier',
    estimatedTime: '4-7 business days',
    tags: ['bank', 'account', 'financial', 'auto-debit'],
  },
  {
    id: 'cat-006',
    requestCode: 'POLICY_REINSTATE',
    requestName: 'Policy Reinstatement',
    description: 'Request to reinstate a lapsed policy',
    category: 'Policy Management',
    slaHours: 120,
    slaDays: 5,
    requiresApproval: true,
    approvalLevels: 2,
    eligibilityRules: [
      {
        id: 'rule-009',
        ruleCode: 'POLICY_LAPSED',
        ruleName: 'Policy Must Be Lapsed',
        ruleDescription: 'Reinstatement is only applicable for lapsed policies',
        ruleType: 'PolicyStatus',
        operator: 'equals',
        fieldName: 'status',
        expectedValue: 'Lapsed',
        errorMessage: 'Reinstatement request can only be raised for lapsed policies',
        isMandatory: true,
        sequence: 1,
      },
      {
        id: 'rule-010',
        ruleCode: 'WITHIN_REVIVAL_PERIOD',
        ruleName: 'Within Revival Period',
        ruleDescription: 'Policy must be within the revival period (usually 5 years from lapse date)',
        ruleType: 'DateBased',
        operator: 'lessThan',
        fieldName: 'yearsSinceLapse',
        expectedValue: 5,
        errorMessage: 'The revival period has expired. Policy cannot be reinstated.',
        isMandatory: true,
        sequence: 2,
      },
    ],
    requiredDocuments: [
      {
        id: 'doc-008',
        documentCode: 'HEALTH_DEC',
        documentName: 'Health Declaration Form',
        description: 'Health declaration / Good health form',
        isMandatory: true,
        acceptedFormats: ['.pdf'],
        maxSizeInMB: 5,
      },
      {
        id: 'doc-009',
        documentCode: 'PREMIUM_RECEIPT',
        documentName: 'Arrear Premium Payment Proof',
        description: 'Payment receipt for arrear premiums',
        isMandatory: true,
        acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
        maxSizeInMB: 5,
      },
    ],
    formSchema: {
      isMultiStep: false,
      sections: [
        {
          id: 'sec-reinstate',
          title: 'Reinstatement Details',
          fields: [
            {
              id: 'fld-reinstate-reason',
              fieldName: 'reinstatementReason',
              fieldLabel: 'Reason for Reinstatement Request',
              fieldType: 'textarea',
              isRequired: true,
              displayOrder: 1,
              columnSpan: 2,
            },
            {
              id: 'fld-health-good',
              fieldName: 'isInGoodHealth',
              fieldLabel: 'I confirm that I am currently in good health',
              fieldType: 'checkbox',
              isRequired: true,
              displayOrder: 2,
            },
          ],
        },
      ],
    },
    isActive: true,
    displayOrder: 6,
    icon: 'ArrowCounterclockwise',
    estimatedTime: '5-7 business days',
    tags: ['reinstatement', 'revival', 'lapsed'],
  },
];

export const mockRequests: ServiceRequest[] = [
  {
    id: 'req-001',
    requestNumber: 'SR20240847123',
    requestTypeCode: 'ADDR_CHG',
    requestTypeName: 'Address Change',
    policyId: 'pol-001',
    policyNumber: 'LI-2021-00147832',
    policyHolderId: 'cust-001',
    policyHolderName: 'Rajesh Sharma',
    status: 'PendingApproval',
    priority: 'Medium',
    submittedBy: 'cust-001',
    submittedByName: 'Rajesh Sharma',
    submittedOn: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    assignedTo: 'agent-001',
    assignedToName: 'Priya Verma',
    assignedOn: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    currentApprovalLevel: 1,
    totalApprovalLevels: 1,
    slaDeadline: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    slaBreached: false,
    slaHoursRemaining: 6,
    requestData: {
      addressType: 'Permanent',
      newAddressLine1: '88, Green Park Apartments',
      newAddressLine2: 'Near Metro Station',
      newCity: 'New Delhi',
      newState: 'Delhi',
      newPincode: '110016',
    },
    oldValues: {
      line1: '42, Sunrise Apartments',
      line2: 'Sector 14, Dwarka',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110078',
    },
    newValues: {
      line1: '88, Green Park Apartments',
      line2: 'Near Metro Station',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110016',
    },
    attachments: [
      {
        id: 'att-001',
        requestId: 'req-001',
        documentCode: 'ADDR_PROOF',
        documentName: 'Address Proof',
        fileName: 'aadhaar_address.pdf',
        fileSize: 524288,
        mimeType: 'application/pdf',
        uploadedBy: 'cust-001',
        uploadedOn: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'Verified',
        verifiedBy: 'agent-001',
        verifiedOn: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        storageUrl: '/attachments/att-001',
        isDeleted: false,
      },
    ],
    statusHistory: [
      {
        id: 'hist-001',
        requestId: 'req-001',
        fromStatus: 'Draft',
        toStatus: 'Submitted',
        changedBy: 'cust-001',
        changedByName: 'Rajesh Sharma',
        changedOn: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        isSystemGenerated: false,
      },
      {
        id: 'hist-002',
        requestId: 'req-001',
        fromStatus: 'Submitted',
        toStatus: 'ValidationPending',
        changedBy: 'system',
        changedByName: 'System',
        changedOn: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 30000).toISOString(),
        isSystemGenerated: true,
      },
      {
        id: 'hist-003',
        requestId: 'req-001',
        fromStatus: 'ValidationPending',
        toStatus: 'EligibilityCheckPassed',
        changedBy: 'system',
        changedByName: 'System',
        changedOn: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 60000).toISOString(),
        isSystemGenerated: true,
      },
      {
        id: 'hist-004',
        requestId: 'req-001',
        fromStatus: 'EligibilityCheckPassed',
        toStatus: 'PendingApproval',
        changedBy: 'system',
        changedByName: 'System',
        changedOn: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
        remarks: 'Assigned to Priya Verma for approval',
        isSystemGenerated: true,
      },
    ],
    approvals: [
      {
        id: 'appr-001',
        requestId: 'req-001',
        approvalLevel: 1,
        approverRole: 'ServicingAgent',
        approverId: 'agent-001',
        approverName: 'Priya Verma',
        status: 'Pending',
        requestedOn: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
        isMandatory: true,
      },
    ],
    comments: [
      {
        id: 'cmt-001',
        requestId: 'req-001',
        commentText: 'Address proof has been verified. Awaiting final approval.',
        commentedBy: 'agent-001',
        commentedByName: 'Priya Verma',
        commentedByRole: 'ServicingAgent',
        commentedOn: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        isInternal: false,
        isEdited: false,
      },
    ],
    correlationId: 'corr-001-2024',
    source: 'Portal',
    channel: 'Customer',
    createdOn: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    modifiedOn: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-002',
    requestNumber: 'SR20240612456',
    requestTypeCode: 'NOM_CHG',
    requestTypeName: 'Nominee Change',
    policyId: 'pol-002',
    policyNumber: 'EN-2019-00089541',
    policyHolderId: 'cust-002',
    policyHolderName: 'Anita Patel',
    status: 'Completed',
    priority: 'Medium',
    submittedBy: 'cust-002',
    submittedByName: 'Anita Patel',
    submittedOn: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    completedOn: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    currentApprovalLevel: 2,
    totalApprovalLevels: 2,
    slaBreached: false,
    requestData: {
      nomineeName: 'Meera Patel',
      nomineeRelationship: 'Daughter',
      nomineeDob: '2008-04-15',
      nomineeShare: 25,
    },
    attachments: [],
    statusHistory: [
      {
        id: 'hist-005',
        requestId: 'req-002',
        fromStatus: 'Draft',
        toStatus: 'Submitted',
        changedBy: 'cust-002',
        changedByName: 'Anita Patel',
        changedOn: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        isSystemGenerated: false,
      },
      {
        id: 'hist-006',
        requestId: 'req-002',
        fromStatus: 'Approved',
        toStatus: 'Completed',
        changedBy: 'system',
        changedByName: 'System',
        changedOn: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        remarks: 'Nominee updated successfully in policy records',
        isSystemGenerated: true,
      },
    ],
    approvals: [],
    comments: [],
    correlationId: 'corr-002-2024',
    source: 'Portal',
    channel: 'Customer',
    createdOn: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    modifiedOn: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-003',
    requestNumber: 'SR20240923789',
    requestTypeCode: 'PREM_MODE_CHG',
    requestTypeName: 'Premium Mode Change',
    policyId: 'pol-003',
    policyNumber: 'ULIP-2022-00234156',
    policyHolderId: 'cust-003',
    policyHolderName: 'Suresh Mehta',
    status: 'Submitted',
    priority: 'High',
    submittedBy: 'cust-003',
    submittedByName: 'Suresh Mehta',
    submittedOn: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    currentApprovalLevel: 0,
    totalApprovalLevels: 0,
    slaDeadline: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
    slaBreached: false,
    slaHoursRemaining: 20,
    requestData: {
      currentMode: 'Monthly',
      newPremiumMode: 'Quarterly',
      effectiveDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    },
    attachments: [],
    statusHistory: [
      {
        id: 'hist-007',
        requestId: 'req-003',
        fromStatus: 'Draft',
        toStatus: 'Submitted',
        changedBy: 'cust-003',
        changedByName: 'Suresh Mehta',
        changedOn: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        isSystemGenerated: false,
      },
    ],
    approvals: [],
    comments: [],
    correlationId: 'corr-003-2024',
    source: 'Portal',
    channel: 'Customer',
    createdOn: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    modifiedOn: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
];
